// GENERATED by scripts/optimize-images.mjs from assets-src/images/catalog.json. Do not edit.
// Regenerate with `npm run images`.

export type ImageCategory = "hero" | "goats" | "rooms" | "restaurant" | "history" | "staff" | "landscape" | "events";

export interface ImageEntry {
  readonly category: ImageCategory;
  /** Intrinsic size of the original (the aspect ratio of every variant). */
  readonly width: number;
  readonly height: number;
  /** Generated widths, ascending. */
  readonly widths: readonly number[];
  /** Content hash used in the file names. */
  readonly hash: string;
  /** Focal point as 0..1 fractions, used for object-position when cropping. */
  readonly focal: { readonly x: number; readonly y: number };
  /** Tiny blurred placeholder as a data URI. */
  readonly lqip: string;
}

/** JPEG fallbacks are only generated up to this width. */
export const JPEG_MAX_WIDTH = 800;

export const IMAGES = {
  "tramonto-colline": {"category":"landscape","width":2000,"height":1204,"widths":[480,800,1200,1600],"hash":"37730128","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAoAA4BaJZACdADzpS9BxAAA4B0EPqQZWvaWwyVB8ssmeNAIWBIa9e/mia768BAAAA=="},
  "ingresso-cascina-magnolia": {"category":"landscape","width":1500,"height":2000,"widths":[480,800,1200],"hash":"34a00a8d","focal":{"x":0.45,"y":0.4},"lqip":"data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JQBYdgx3EtHocDj+XExAA4YwbWbE0SWpU2ET5Ppy8KJ1lGyq4vjpLuY0yfrMNV40mPAaWGauM+8hflIWgAAAA"},
  "cascina-prato-estate": {"category":"hero","width":2048,"height":1536,"widths":[480,800,1200,1600,2000],"hash":"633dea2a","focal":{"x":0.65,"y":0.55},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQAAwAA4BaJbACdAD0ZlFuGwTSAADx18XmNx7zldwraE5/VSxLiy+QCMzPz33NwBH2gBJzRUyggAAA"},
  "sala-ristorante-tavolata": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"c799a638","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAwAA4BaJZACdACIYjNBAAD+3dizxRF7NNYPsx5v5qetZw4VaLzp7Jg25dglyJSyFfI0XR9oKFeAAAA="},
  "sala-ristorante-camino": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"8f76bd91","focal":{"x":0.4,"y":0.55},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQAAwAA4BaJbACdAD0OIchMiQAAM4zcc998aLFNIWvpLpV9UnNl6X7Su9dbqR9/e9MPAs3K+pQXcLEqAA="},
  "sala-ristorante-travi": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"00a1b5b9","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQAAwAA4BaJbACdAELYLQGbRNpAAD+8MudNKxNsD5zLmryO9Tk0o33Af88YcDqaLuQvDkLCZgQwAAA"},
  "tavola-margherite": {"category":"restaurant","width":1500,"height":2000,"widths":[480,800,1200],"hash":"72a91e12","focal":{"x":0.5,"y":0.45},"lqip":"data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JaACdMoACTzW/yNFJTm9aAAD9/IJpBrNF6dqoPB6eCZtMOJAciPjM2HWRqJ1JL1R4CIInUbnbVirzylgNtvb/Oi/yh0HGoOsDGnglSwXTARlr4rrjqFrdnHTm/gAA"},
  "sala-ristorante-tavoli": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"03103ffb","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJbACdAD0SNSkIQAA/ulfRqLt5SxUiCHrn1b/Ultt2jKC2jPaGlXIR/livM+gfCptlOW8MiOVO7AA"},
  "sala-ristorante-fiori": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"5267cc26","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJbACdAEOzLhaXmAA/qn/EZYuSKdLSeLb4+x0aVFx1u5AYS8lMGJZUH0ZtYpPW9q+bgzeKtWAAA=="},
  "sala-ristorante-angolo": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"505276b6","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAwAA4BaJbACdADpJbE33vmIAAD0dHDNNJMiDaMqnxZHIg9z7H4+PDuCKum34/1m7ht8QeTgYcMRlHddovLpJWjXexIbsTBKAAAA"},
  "tavolata-pergolato-fronte": {"category":"restaurant","width":1500,"height":2000,"widths":[480,800,1200],"hash":"8f380e57","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JbACsACPMduFgnu8yI2cAAP69k9L2TFa1JftVuIQKnwYbcz3FHl0fV+yUn0ozOtx54YPHnjVR+qfn480MRrgYYj7ym8mxN4yGezORw+d2SPwAAAA="},
  "tavolata-pergolato": {"category":"restaurant","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"91ea34df","focal":{"x":0.55,"y":0.55},"lqip":"data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJbACdADPCYMHtZoAAP6JNgLdts+cVdz5OrAxzPSNHX72HX8L3KYZeKYB8VPV7L60ZkEzHXEUsjJWx5AAAA=="},
  "tavolo-finestra-gialla": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"c1a141b1","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAgCdASoQAAwAA4BaJbACdAD7FmXd59wgjgAA/mcjj228BqbNKx0wI2pmqHsBqOtt0hI8RBf9CEh89YGsdPnwLkk7fC54AAA="},
  "cuscino-cuore-camera": {"category":"rooms","width":1500,"height":2000,"widths":[480,800,1200],"hash":"71677a4b","focal":{"x":0.6,"y":0.6},"lqip":"data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoQABUAPu1Ct1apoqakGAEwHYlAE6ZQAGqCvIRqecj57E+cAP7jK7cFboF+J9L+NiIKKIIfMCKSpig3OG4DY5kDu52kBCcAAAA="},
  "camera-scala-ferro": {"category":"rooms","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"62b109e4","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJZACdADRFeCffgAA/rpwFsABhGggrjNRXWWiQfoCUSNW0sJI8MUKR/612vCzNIG5m6cw9uS6GtAA"},
  "camera-pietra-letto-ferro": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"e8186888","focal":{"x":0.45,"y":0.6},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJagCdAENBxfE68AA/uzDoTDQWQatLNr6UZDZo9TUp4nFxUPteXkrU30fjHNb08r1Lwg1Vk57cAAA"},
  "camera-letto-ferro-verticale": {"category":"rooms","width":768,"height":1024,"widths":[480],"hash":"15f822d7","focal":{"x":0.5,"y":0.65},"lqip":"data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoRwJoAD4udZKZSNrHo0gAD+8MyvGOgoKSodgQsKiAMm2iOQuC3ivwCcZoI3KX0GtOwEniOs+pl0D+EqSddayUSOiTJ0fTmpflRJxA3PKkIeARzgAAA="},
  "camera-pietra-lampada": {"category":"rooms","width":1080,"height":851,"widths":[480,800],"hash":"9d28d63f","focal":{"x":0.4,"y":0.65},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAA0AA4BaJaACdAERH7VO6AAA/vEhYzbCN66mgOXFvcPpfvaNpqGfqReg1hiNwyCs8x1TuXasMJ4vZTdQXAAA"},
  "camera-copriletto-fiori": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"92d0de0b","focal":{"x":0.4,"y":0.6},"lqip":"data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAwAA4BaJbACdADjesSwFBV7wAD+QzhpfnRNMJN3w5Rv2mcSYashLSqHJzk2moLavAj9n720rwkLOFubg7eVaiQYMRUAAAA="},
  "camera-copriletto-fiori-scala": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"b406b5db","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAwAA4BaJbACdADcOj23GEXAAP7sjdMD++LQqVFD07BJ8qiwfkwVxZAOFpeuGZAuEzvBl71LgAAA"},
  "arpista-nel-bosco": {"category":"events","width":1500,"height":2000,"widths":[480,800,1200],"hash":"6556732b","focal":{"x":0.55,"y":0.55},"lqip":"data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABUAPu1mqk2ppaQiMAgBMB2JYwC7ACBy8i83KTb40fAA61SK7GwDTvnZxcN//w6eE+c0ZqovKrnLINKDEIwVhSKeeAAA"},
  "cena-nel-bosco": {"category":"events","width":1064,"height":1445,"widths":[480,800],"hash":"136321e6","focal":{"x":0.55,"y":0.65},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoQABYAPu1orU2ppqSiMAgBMB2JZAC7AGlgXclYyeTceqvPAAD+7uqxM4O5Umq4MQ3nJBYoxW3f4HzJz7J0DHpySwlxPcwsEEKVeywOLFyigzxTmLSWbH5uVdY+4lu48jmwDhujUAA="},
  "tavoli-giardino-rosa": {"category":"events","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"d5beed2e","focal":{"x":0.4,"y":0.55},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAwAA4BaJagCdAENo7tk//wAAP7p7d0TENb7jz4UyDdLXQvTAN8jWBFgxbomz3RnPk7BH1DqSzkh9sAAAA=="},
  "cena-a-lume-di-candela": {"category":"events","width":1078,"height":1391,"widths":[480,800],"hash":"bf8e69a3","focal":{"x":0.6,"y":0.6},"lqip":"data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABUAPu1iqU2ppaOyMAgCQB2JYwCsACHPhr1ephi2jhAA/uv0MJjYQjAHbe8Z9uTlFLq44Vus5Tlh4vJj+8licGCq20AA"},
  "cena-giardino-sera": {"category":"events","width":1080,"height":1234,"widths":[480,800],"hash":"67d1794c","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABQAwCdASoQABIAPu1iqU2ppaOvMAgB4B2JQBfnAtuNrDHioAD18aHVvtOfZTDBPWyaGcXeIEAspdafcGa3i5SYTKLAAA=="},
  "cena-luci-sera": {"category":"events","width":1080,"height":1265,"widths":[480,800],"hash":"fcb2edb1","focal":{"x":0.5,"y":0.7},"lqip":"data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABMAPu1iqU2ppaOiMAgBMB2JYgC7ACHZyHsfUSvfAAD+GHQJ1SZsdg+8JV77ObIOTkZGmXPBACE65gd1tUoyl0gnCsf2iAAAAA=="},
  "cascina-illuminata-sera": {"category":"events","width":1080,"height":603,"widths":[480,800],"hash":"c0fbe8bb","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAkAA4BaJagCdAEUoSQkiAAA/ukDDDYs6wVoqNweCjasXUcu2bG+gbv5rLiUq52AAA=="},
  "cascina-magnolia": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"0e240113","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAwAA4BaJYgCdADPm2uOiB5kAPHdiLSDcP9Rh4YVc/l7WiwSbnyT6TndoeWUNCGcLy6odozEAAAA"},
  "cascina-facciata-pietra": {"category":"landscape","width":1066,"height":1081,"widths":[480,800],"hash":"dd687c5e","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQABAAA4BaJbACdACZbJgGgAD9RtXzAtcMcXPVra+sKm9ZoHuqmAai4ujMTJaWowafj0SQx76vQmM/qwcXym5TOiSAAA=="},
  "cascina-portico-estate": {"category":"landscape","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"118b7f10","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAwAA4BaJZgCdAERG8W4MgAA/mWXEK010v2Dwx94cYBbUpd1pGZZKDLh7zeYBTZBK3HlLGgAAA=="},
  "capre-al-pascolo": {"category":"goats","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"7214ab97","focal":{"x":0.5,"y":0.7},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAwAA4BaJagCdAEO9KGtzgAA/nZ4/dls/LCrfUn6nj1Q8mK4S8bJctMExNeyhf4NCXpO39AoDpAAAAA="},
  "cancello-glicine": {"category":"landscape","width":1071,"height":1407,"widths":[480,800],"hash":"ead3d227","focal":{"x":0.45,"y":0.6},"lqip":"data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdACEl0c/jLp8mQAD9Qh2drXJW7TGeiQxffLHTiM6+uCsIYz/C71ZxHtKfVB5h7ashxRgfZZhl6I2hZeXv2lPWHgAA"},
  "cascina-dal-prato": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"bef411ee","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAwAA4BaJbACdABzaGAA/kbtII67U3PFoH0z+Jwz9Al9CnN+4pxpYN3Kna2y356BVK4+sKyMhQAA"},
  "cortile-gerani": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"130b2ade","focal":{"x":0.35,"y":0.5},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJaACdAC6fHXhIgAA/ZqAw8x+DQNA8V8SNYVEV/lACYdJUjL8pE+pPq2aq9se8LxYatx6MqiAAA=="},
  "capre-sotto-la-cascina": {"category":"goats","width":1536,"height":2048,"widths":[480,800,1200],"hash":"4f0bbc2f","focal":{"x":0.5,"y":0.75},"lqip":"data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZACw7B5qsMfDqvd34AD9H2kIfhojEeHTndFqJ8YRIDperN1vTQnG6TfMUumk9OGCtmrOyIvBUV+2SpD3MsI6wAA="},
  "capretto-nel-fieno": {"category":"goats","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"d1dc1026","focal":{"x":0.4,"y":0.65},"lqip":"data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAwAA4BaJYgC7AEKKNAAAP39HBZmBtmuteWKxBOnvM/mAmYVJDn4UL+ORd8ZOYCA0YDgAAA="},
  "salumeria-impasto-salsiccia": {"category":"staff","width":1200,"height":1600,"widths":[480,800,1200],"hash":"f1a9dc74","focal":{"x":0.5,"y":0.35},"lqip":"data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JaACdMoAByx6vOr/C2xwA/HO96DUrItbYNQ/jWcsXQWXZgYYRF4YAye24NrvgIEzeF2ohtl03LraCEqlrAAAA"},
  "salumeria-macinatrice-carne": {"category":"staff","width":838,"height":1880,"widths":[480,800],"hash":"64ccabf6","focal":{"x":0.5,"y":0.3},"lqip":"data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoQACQAPu1kqk6ppaOiKqwBMB2JYwCw7D+uKXUdYjoneNzq5TgSu4wAAP7wCpBWPo4CkOWmTKXpP7o0VmlFHRNnPfvCQzRKU9cJqKhiIjUt8Oq1ZT64+atLrD0XkY3OZudHWf9vftUf6WNGaeQ1sv60WtxZXv0lfzopHnsNDlW0NwAA"},
  "capretti-intorno-allevatore": {"category":"goats","width":2044,"height":2048,"widths":[480,800,1200,1600],"hash":"f437411d","focal":{"x":0.6,"y":0.45},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQABAAA4BaJZgCdAD0fI9+D5eQAP6yEm6h9t9SlHT6ssYsxgyGyvR2Uzh1JXMAoj9KtdZgvrDQdugA"},
  "vigneti-sotto-la-neve": {"category":"landscape","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"ce47696b","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoQAAwAA4BaJZwAApB0ShAA/tS5nklMjxhOVsVdEosbtSmeo0b9EDgA"},
  "cuoca-con-salumi-e-pane": {"category":"staff","width":1200,"height":1600,"widths":[480,800,1200],"hash":"b564fff3","focal":{"x":0.5,"y":0.35},"lqip":"data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JQBdgBDWBUahimbZA04AA/vM0x3M5wYaJu7RCowkGb71XmQHEYVgiWOssbCw01y3AOzyhGPnxq0zbkE0ARRKw301JVCsAAAA="},
  "uomo-capretto-bianco-nero-stalla": {"category":"goats","width":1500,"height":2000,"widths":[480,800,1200],"hash":"04b4ab8c","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7ACG8AkDD1IJFvGqAAP7oxqr9L7bMI/H8BbZHQ7m7CahBGjHzr1IWg+HBWp/D8ARrMDJzPgYjQ00P0TApo9t60fpXy30CSf4UAAA="},
  "uomo-capretto-bianco-biberon": {"category":"goats","width":1500,"height":2000,"widths":[480,800,1200],"hash":"6b468c15","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoQABUAPu1kqU2ppaQiMAgBMB2JZQC7ABuijSFbq3DsDQ4AAP7ytNQqQMXKn8dZ2vzbN3xT8pTINjoXZ4mSBUJ/uoKKrGmK7Oxw6kZXCr3E9m0gtFEMN/BJF/qyLy1DkJuAAA=="},
  "uomo-pergolato-felpa-capre": {"category":"staff","width":1102,"height":1762,"widths":[480,800],"hash":"856a5101","focal":{"x":0.5,"y":0.4},"lqip":"data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoQABoAPu1iqk4ppaQiMAgBMB2JYgCdIMgCvatpWos/xF2qtAD+yPID+98XpqcQ194Em/HhvRHjbh3zTDkzhXuAr11TzATXc6h+H8+6ZnyCT3FNFisZDyK/EDeikqBZ64RFy9AA"},
  "uomo-capretto-bianco-guanti-stalla": {"category":"goats","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"05cf4e9e","focal":{"x":0.5,"y":0.4},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAwAA4BaJZwAAtrkwQPYAAD++E6b9Ts/r8G+zXGU0Uv/VkkWsKWE/DDqVPxFmIzpukbigAIdWICwAAA="},
  "uomo-potatura-rose-giardino": {"category":"staff","width":1500,"height":2000,"widths":[480,800,1200],"hash":"c73a3fd9","focal":{"x":0.6,"y":0.35},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoQABUAPu1kqk4ppaQiMAgBMB2JZgBTAAXihv+9QwBELoAA/vHXNOG4Jr/dCCqniCFKphBrqIQonDA/Mwz/qNRmAUskr4RnGZoW5skQuns4E6s/iSohp/AioiPdwRSFwLzO0TSwAAA="},
  "donna-capretto-nero-stalla": {"category":"goats","width":1500,"height":2000,"widths":[480,800,1200],"hash":"b420b09b","focal":{"x":0.45,"y":0.35},"lqip":"data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoQABUAPu1iqk4ppaQiMAgBMB2JZACdMoADNlON7AGXwz/2AAD6LgUYwAAjQqeahN5BXrl9MEf3nZh3QzK/+f9qa5exGmg5+SwyS6aknDt7Jhzyx5D7xNpm+4DSIgSmgcGQTgAA"},
  "donna-torta-berretto-natale": {"category":"staff","width":1080,"height":1920,"widths":[480,800],"hash":"435b8bd6","focal":{"x":0.55,"y":0.35},"lqip":"data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABwAPu1mq04ppaQiMAgBMB2JYgCw7BX7u74ZJXH+l2DAAP5W35Y/a7IUJfQXhSleA+JWbRS2zBd0TDJt5xNkosjzGH6zms7O1ort386ulONk/NMK2AvI/lXqvK7X8/7mLMBm9A3rIASLXXHJKPEN3VokFSfi+O6pd4buky+6DgOi997qlVYAAAA="},
  "capre-prato-cascina-primavera": {"category":"goats","width":1500,"height":2000,"widths":[480,800,1200],"hash":"e9837ccc","focal":{"x":0.5,"y":0.45},"lqip":"data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JYgC7LwAB0ZzX6D8oAADKev6LCJfP+gGXh4SHfG/nYML2bjJiiOilioMXx2r10J+Z6j1Ja/T+AA=="},
  "capre-pascolo-prato-inverno": {"category":"goats","width":1500,"height":2000,"widths":[480,800,1200],"hash":"885952c7","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JZQCdACHc70yjeAVUbkAA/sf85SJze1JEmnMwd5rmVFgx9ZZNptKakbpNdMA7OYNYeFIu0SW0rwAA"},
  "coppia-abbraccia-capra-portico": {"category":"staff","width":1227,"height":1682,"widths":[480,800,1200],"hash":"5fe971d9","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABYAPu1iqU2ppaOiMAgBMB2JYgCdABeD9yVNzf39vIFOAP4yGl9Is10nPEQYoExk8K8qTZCAsjslh69eyD4maHNs5vlvczCJvduKz68vV5vs7BFkAAAA"},
  "sala-natale-coppia-tavola": {"category":"restaurant","width":1500,"height":2000,"widths":[480,800,1200],"hash":"606540cf","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoADQMgjOU2Nn1CRwAD+6NAaN9GVHId/QsW7ie7+pxaV8yoaiNKy9TgGQy5k38J0w3wh+iE1uhqreoMoCvzErkJlAlc3DLoaRcbDTgTntfe347nTjdcmr+QAAAA="},
  "donna-capretto-bianco-grembiule": {"category":"goats","width":1008,"height":2016,"widths":[480,800],"hash":"71ead4bf","focal":{"x":0.5,"y":0.4},"lqip":"data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoQACAAPu1iqU2ppaOiMAgBMB2JYwCw83gAbyZPcAHuMwUMmi/SwAD+7L9GZ/6NLiD1X6fOplw0oMqxzk/Adz1OO0dpG7slSAGUR6y7x0H+DSgARQaTGIfaqyQdURHG74+zlIaaFfch/Z1lHL+nLUNsi05HDrdAAAA="},
  "coppia-brindisi-ingresso": {"category":"staff","width":1500,"height":2000,"widths":[480,800,1200],"hash":"c099b2ba","focal":{"x":0.5,"y":0.4},"lqip":"data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAk2TdOtZmi1p0kAA4RNAEABU/cxal7EeTEnPJPYhwTt8WulJIp5NCVilKbtEYcCafvav7W3vdgAAAA=="},
  "coppia-selfie-capre-recinto": {"category":"staff","width":1080,"height":826,"widths":[480,800],"hash":"1bc693b2","focal":{"x":0.5,"y":0.4},"lqip":"data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAwAA4BaJZQCdAEe3wrb+augAP3V3KeHpaaxymdrv+QE9xvM522CWIw4QBOS0sZa4AAA"},
  "uomo-grembiule-saluta-ingresso": {"category":"staff","width":1079,"height":1928,"widths":[480,800],"hash":"e32ec218","focal":{"x":0.5,"y":0.35},"lqip":"data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAwCdASoQAB0ALrV2u12jqampiYC0SxgFYAIZV1rK9R+hIQAA/nFgn3LI6iQNE1ijMHYB84yjpiNzbEPHfaJuDrjxUcgFhg4IMTuqTSH49B1rOc/BRn/9W5QTt1gc/RBZzzQNQ4AAAA=="},
  "capretti-giocano-con-allevatore": {"category":"goats","width":1080,"height":1195,"widths":[480,800],"hash":"e5276fac","focal":{"x":0.45,"y":0.5},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAgCdASoQABIAPu1iqU2ppaQiMAgBMB2JZQC3uANEAADdQFcSiFHv03toBQQZfUfBg92/8snkITTzorSN9rO9kREAAA=="},
  "uomo-trattore-recinto": {"category":"staff","width":1080,"height":1486,"widths":[480,800],"hash":"d7f165f5","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoQABYAPu1iqk2ppaQiMAgBMB2JYgC7MoADTekcsaPukiWEAAD+4vE9ZaW9yrtL1odOnetbXcl7LHdhPjp2TUsJ4e1HkrU+S+L+4lf5N+xObtR+UrqIFC4x78U3VYzmNsLoxysAAAA="},
} as const satisfies Record<string, ImageEntry>;

export type ImageSlug = keyof typeof IMAGES;

/** Localized alt text. IDs are `img.<slug>.alt`. */
export const IMAGE_ALTS: Record<ImageSlug, string> = {
  "tramonto-colline": $localize`:@@img.tramonto-colline.alt:Cielo rosa e azzurro al tramonto sopra le colline e la pianura.`,
  "ingresso-cascina-magnolia": $localize`:@@img.ingresso-cascina-magnolia.alt:Ingresso della cascina in pietra, con i fiori di magnolia in primo piano.`,
  "cascina-prato-estate": $localize`:@@img.cascina-prato-estate.alt:La cascina in pietra su un prato verde, sotto un cielo azzurro.`,
  "sala-ristorante-tavolata": $localize`:@@img.sala-ristorante-tavolata.alt:Sala del ristorante con una lunga tavola apparecchiata e tovaglie a quadretti rossi.`,
  "sala-ristorante-camino": $localize`:@@img.sala-ristorante-camino.alt:Sala del ristorante con il camino, le travi di legno e i tavoli apparecchiati.`,
  "sala-ristorante-travi": $localize`:@@img.sala-ristorante-travi.alt:Tavolo apparecchiato davanti al camino, sotto le travi di legno.`,
  "tavola-margherite": $localize`:@@img.tavola-margherite.alt:Tavola apparecchiata vista dall'alto, con un centrotavola di margherite.`,
  "sala-ristorante-tavoli": $localize`:@@img.sala-ristorante-tavoli.alt:Tavoli apparecchiati nella sala del ristorante, con le pareti color terracotta.`,
  "sala-ristorante-fiori": $localize`:@@img.sala-ristorante-fiori.alt:Tavoli apparecchiati nella sala, con un vaso di fiori in primo piano.`,
  "sala-ristorante-angolo": $localize`:@@img.sala-ristorante-angolo.alt:Angolo della sala con una finestra, tavoli a quadretti e decorazioni.`,
  "tavolata-pergolato-fronte": $localize`:@@img.tavolata-pergolato-fronte.alt:Lunga tavola apparecchiata sotto il pergolato, con un calice in primo piano.`,
  "tavolata-pergolato": $localize`:@@img.tavolata-pergolato.alt:Lunga tavola apparecchiata all'aperto, sotto il pergolato e davanti al muro di pietra.`,
  "tavolo-finestra-gialla": $localize`:@@img.tavolo-finestra-gialla.alt:Tavolo all'aperto davanti a una finestra gialla, con gerani rossi e un muro di pietra.`,
  "cuscino-cuore-camera": $localize`:@@img.cuscino-cuore-camera.alt:Cuscino ricamato con un cuore rosso sul letto, davanti a un muro di pietra.`,
  "camera-scala-ferro": $localize`:@@img.camera-scala-ferro.alt:Camera con letto matrimoniale, soffitto di legno e una scala di ferro.`,
  "camera-pietra-letto-ferro": $localize`:@@img.camera-pietra-letto-ferro.alt:Camera con muro di pietra, letto in ferro battuto e lampada accesa.`,
  "camera-letto-ferro-verticale": $localize`:@@img.camera-letto-ferro-verticale.alt:Camera con letto in ferro battuto, muro di pietra e pavimento in cotto.`,
  "camera-pietra-lampada": $localize`:@@img.camera-pietra-lampada.alt:Camera con muro di pietra, letto in ferro battuto e lampada sul comodino.`,
  "camera-copriletto-fiori": $localize`:@@img.camera-copriletto-fiori.alt:Camera con copriletto a fiori, muro di pietra e finestra con vetri colorati.`,
  "camera-copriletto-fiori-scala": $localize`:@@img.camera-copriletto-fiori-scala.alt:Camera con copriletto a fiori, comò antico e scala a chiocciola.`,
  "arpista-nel-bosco": $localize`:@@img.arpista-nel-bosco.alt:Una musicista suona l'arpa nel bosco, accanto a un vaso di fiori.`,
  "cena-nel-bosco": $localize`:@@img.cena-nel-bosco.alt:Gruppo di persone a cena all'aperto, tra gli alberi del bosco.`,
  "tavoli-giardino-rosa": $localize`:@@img.tavoli-giardino-rosa.alt:Tavoli apparecchiati all'aperto con tovaglie rosa, tra gli alberi.`,
  "cena-a-lume-di-candela": $localize`:@@img.cena-a-lume-di-candela.alt:Tavoli a lume di candela all'aperto, di sera, con la pianura illuminata sullo sfondo.`,
  "cena-giardino-sera": $localize`:@@img.cena-giardino-sera.alt:Cena all'aperto di sera, con gli ospiti seduti ai lunghi tavoli sotto gli alberi.`,
  "cena-luci-sera": $localize`:@@img.cena-luci-sera.alt:Cena all'aperto di sera, sotto una fila di lucine appese tra gli alberi.`,
  "cascina-illuminata-sera": $localize`:@@img.cascina-illuminata-sera.alt:La cascina illuminata di sera, con gli ospiti sotto il portico.`,
  "cascina-magnolia": $localize`:@@img.cascina-magnolia.alt:La cascina in pietra vista dall'ingresso, con un albero di magnolia in fiore.`,
  "cascina-facciata-pietra": $localize`:@@img.cascina-facciata-pietra.alt:La facciata in pietra della cascina, con il balcone di legno e il cielo azzurro.`,
  "cascina-portico-estate": $localize`:@@img.cascina-portico-estate.alt:Il lato della cascina con il portico, il pergolato e il prato in estate.`,
  "capre-al-pascolo": $localize`:@@img.capre-al-pascolo.alt:Un gruppo di capre bianche al pascolo su un prato verde.`,
  "cancello-glicine": $localize`:@@img.cancello-glicine.alt:Il cancello della cascina con il glicine in fiore.`,
  "cascina-dal-prato": $localize`:@@img.cascina-dal-prato.alt:La cascina vista dal prato, tra alberi e fiori.`,
  "cortile-gerani": $localize`:@@img.cortile-gerani.alt:Il cortile in pietra con la facciata della cascina e vasi di gerani.`,
  "capre-sotto-la-cascina": $localize`:@@img.capre-sotto-la-cascina.alt:Capre bianche e marroni al pascolo sul prato sotto la cascina.`,
  "capretto-nel-fieno": $localize`:@@img.capretto-nel-fieno.alt:Un capretto bianco e nero riposa nel fieno, vicino a un tronco.`,
  "salumeria-impasto-salsiccia": $localize`:@@img.salumeria-impasto-salsiccia.alt:Un uomo sorride davanti a un grande mucchio di carne macinata, con costine appese alle sue spalle.`,
  "salumeria-macinatrice-carne": $localize`:@@img.salumeria-macinatrice-carne.alt:Un uomo in grembiule lavora con la macinatrice nel laboratorio dei salumi.`,
  "capretti-intorno-allevatore": $localize`:@@img.capretti-intorno-allevatore.alt:Un uomo seduto sul prato circondato da capretti bianchi, uno dei quali gli sale sulla schiena.`,
  "vigneti-sotto-la-neve": $localize`:@@img.vigneti-sotto-la-neve.alt:I filari di vigna e il bosco coperti di neve in una giornata d’inverno.`,
  "cuoca-con-salumi-e-pane": $localize`:@@img.cuoca-con-salumi-e-pane.alt:Una donna sorridente in cucina porta un vassoio di salumi e un cesto di pane.`,
  "uomo-capretto-bianco-nero-stalla": $localize`:@@img.uomo-capretto-bianco-nero-stalla.alt:Un uomo con il berretto sorride tenendo in braccio un capretto bianco e nero nella stalla.`,
  "uomo-capretto-bianco-biberon": $localize`:@@img.uomo-capretto-bianco-biberon.alt:Un uomo sorridente abbraccia un capretto bianco, con un biberon in mano.`,
  "uomo-pergolato-felpa-capre": $localize`:@@img.uomo-pergolato-felpa-capre.alt:Un uomo in piedi sotto il pergolato, con una felpa con il disegno di una capra.`,
  "uomo-capretto-bianco-guanti-stalla": $localize`:@@img.uomo-capretto-bianco-guanti-stalla.alt:Un uomo con i guanti da lavoro tiene in braccio un capretto bianco nella stalla.`,
  "uomo-potatura-rose-giardino": $localize`:@@img.uomo-potatura-rose-giardino.alt:Un uomo con il cappello cura una pianta di rose nel giardino, sul prato verde.`,
  "donna-capretto-nero-stalla": $localize`:@@img.donna-capretto-nero-stalla.alt:Una donna sorridente tiene in braccio un capretto nero davanti a un muro di pietra.`,
  "donna-torta-berretto-natale": $localize`:@@img.donna-torta-berretto-natale.alt:Una donna con il berretto rosso mostra una torta decorata all’ingresso della cascina, a Natale.`,
  "capre-prato-cascina-primavera": $localize`:@@img.capre-prato-cascina-primavera.alt:Capre bianche al pascolo sul prato davanti alla cascina, in una giornata di primavera.`,
  "capre-pascolo-prato-inverno": $localize`:@@img.capre-pascolo-prato-inverno.alt:Un gruppo di capre al pascolo sul prato, tra gli alberi spogli.`,
  "coppia-abbraccia-capra-portico": $localize`:@@img.coppia-abbraccia-capra-portico.alt:Un uomo e una donna sorridono abbracciando una capra bianca davanti a una porta di legno.`,
  "sala-natale-coppia-tavola": $localize`:@@img.sala-natale-coppia-tavola.alt:Due persone in piedi dietro una tavola apparecchiata per Natale, nella sala con il camino.`,
  "donna-capretto-bianco-grembiule": $localize`:@@img.donna-capretto-bianco-grembiule.alt:Una donna sorridente con il grembiule tiene in braccio un capretto bianco.`,
  "coppia-brindisi-ingresso": $localize`:@@img.coppia-brindisi-ingresso.alt:Un uomo e una donna brindano davanti all’ingresso in pietra della cascina.`,
  "coppia-selfie-capre-recinto": $localize`:@@img.coppia-selfie-capre-recinto.alt:Un uomo e una donna si fanno un selfie davanti al recinto delle capre.`,
  "uomo-grembiule-saluta-ingresso": $localize`:@@img.uomo-grembiule-saluta-ingresso.alt:Un uomo in grembiule saluta dalla porta di pietra della cascina, tra i fiori.`,
  "capretti-giocano-con-allevatore": $localize`:@@img.capretti-giocano-con-allevatore.alt:Capretti bianchi giocano attorno a un uomo seduto a terra, mentre uno gli sale sulla schiena.`,
  "uomo-trattore-recinto": $localize`:@@img.uomo-trattore-recinto.alt:Un uomo sul trattore lavora lungo la recinzione del pascolo, sotto un grande abete.`,
};
