// GENERATED by scripts/optimize-images.mjs from assets-src/images/catalog.json. Do not edit.
// Regenerate with `npm run images`.

export type ImageCategory = "hero" | "goats" | "rooms" | "restaurant" | "history" | "staff" | "landscape" | "events";

export interface ImageEntry {
  readonly category: ImageCategory;
  /** Intrinsic size of the original (the aspect ratio of every variant). */
  readonly width: number;
  readonly height: number;
  /** Generated widths, ascending. */
  readonly widths: readonly number[];
  /** Content hash used in the file names. */
  readonly hash: string;
  /** Focal point as 0..1 fractions, used for object-position when cropping. */
  readonly focal: { readonly x: number; readonly y: number };
  /** Tiny blurred placeholder as a data URI. */
  readonly lqip: string;
}

/** JPEG fallbacks are only generated up to this width. */
export const JPEG_MAX_WIDTH = 800;

export const IMAGES = {
  "tramonto-colline": {"category":"landscape","width":2000,"height":1204,"widths":[480,800,1200,1600],"hash":"37730128","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAoAA4BaJZACdADzpS9BxAAA4B0EPqQZWvaWwyVB8ssmeNAIWBIa9e/mia768BAAAA=="},
  "ingresso-cascina-magnolia": {"category":"landscape","width":1500,"height":2000,"widths":[480,800,1200],"hash":"34a00a8d","focal":{"x":0.45,"y":0.4},"lqip":"data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JQBYdgx3EtHocDj+XExAA4YwbWbE0SWpU2ET5Ppy8KJ1lGyq4vjpLuY0yfrMNV40mPAaWGauM+8hflIWgAAAA"},
  "cascina-prato-estate": {"category":"hero","width":2048,"height":1536,"widths":[480,800,1200,1600,2000],"hash":"633dea2a","focal":{"x":0.65,"y":0.55},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQAAwAA4BaJbACdAD0ZlFuGwTSAADx18XmNx7zldwraE5/VSxLiy+QCMzPz33NwBH2gBJzRUyggAAA"},
  "sala-ristorante-tavolata": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"c799a638","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAwAA4BaJZACdACIYjNBAAD+3dizxRF7NNYPsx5v5qetZw4VaLzp7Jg25dglyJSyFfI0XR9oKFeAAAA="},
  "sala-ristorante-camino": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"8f76bd91","focal":{"x":0.4,"y":0.55},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQAAwAA4BaJbACdAD0OIchMiQAAM4zcc998aLFNIWvpLpV9UnNl6X7Su9dbqR9/e9MPAs3K+pQXcLEqAA="},
  "sala-ristorante-travi": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"00a1b5b9","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQAAwAA4BaJbACdAELYLQGbRNpAAD+8MudNKxNsD5zLmryO9Tk0o33Af88YcDqaLuQvDkLCZgQwAAA"},
  "tavola-margherite": {"category":"restaurant","width":1500,"height":2000,"widths":[480,800,1200],"hash":"72a91e12","focal":{"x":0.5,"y":0.45},"lqip":"data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JaACdMoACTzW/yNFJTm9aAAD9/IJpBrNF6dqoPB6eCZtMOJAciPjM2HWRqJ1JL1R4CIInUbnbVirzylgNtvb/Oi/yh0HGoOsDGnglSwXTARlr4rrjqFrdnHTm/gAA"},
  "sala-ristorante-tavoli": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"03103ffb","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJbACdAD0SNSkIQAA/ulfRqLt5SxUiCHrn1b/Ultt2jKC2jPaGlXIR/livM+gfCptlOW8MiOVO7AA"},
  "sala-ristorante-fiori": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"5267cc26","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJbACdAEOzLhaXmAA/qn/EZYuSKdLSeLb4+x0aVFx1u5AYS8lMGJZUH0ZtYpPW9q+bgzeKtWAAA=="},
  "sala-ristorante-angolo": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"505276b6","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAwAA4BaJbACdADpJbE33vmIAAD0dHDNNJMiDaMqnxZHIg9z7H4+PDuCKum34/1m7ht8QeTgYcMRlHddovLpJWjXexIbsTBKAAAA"},
  "tavolata-pergolato-fronte": {"category":"restaurant","width":1500,"height":2000,"widths":[480,800,1200],"hash":"8f380e57","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JbACsACPMduFgnu8yI2cAAP69k9L2TFa1JftVuIQKnwYbcz3FHl0fV+yUn0ozOtx54YPHnjVR+qfn480MRrgYYj7ym8mxN4yGezORw+d2SPwAAAA="},
  "tavolata-pergolato": {"category":"restaurant","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"91ea34df","focal":{"x":0.55,"y":0.55},"lqip":"data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJbACdADPCYMHtZoAAP6JNgLdts+cVdz5OrAxzPSNHX72HX8L3KYZeKYB8VPV7L60ZkEzHXEUsjJWx5AAAA=="},
  "tavolo-finestra-gialla": {"category":"restaurant","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"c1a141b1","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAgCdASoQAAwAA4BaJbACdAD7FmXd59wgjgAA/mcjj228BqbNKx0wI2pmqHsBqOtt0hI8RBf9CEh89YGsdPnwLkk7fC54AAA="},
  "cuscino-cuore-camera": {"category":"rooms","width":1500,"height":2000,"widths":[480,800,1200],"hash":"71677a4b","focal":{"x":0.6,"y":0.6},"lqip":"data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoQABUAPu1Ct1apoqakGAEwHYlAE6ZQAGqCvIRqecj57E+cAP7jK7cFboF+J9L+NiIKKIIfMCKSpig3OG4DY5kDu52kBCcAAAA="},
  "camera-scala-ferro": {"category":"rooms","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"62b109e4","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJZACdADRFeCffgAA/rpwFsABhGggrjNRXWWiQfoCUSNW0sJI8MUKR/612vCzNIG5m6cw9uS6GtAA"},
  "camera-pietra-letto-ferro": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"e8186888","focal":{"x":0.45,"y":0.6},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJagCdAENBxfE68AA/uzDoTDQWQatLNr6UZDZo9TUp4nFxUPteXkrU30fjHNb08r1Lwg1Vk57cAAA"},
  "camera-letto-ferro-verticale": {"category":"rooms","width":768,"height":1024,"widths":[480],"hash":"15f822d7","focal":{"x":0.5,"y":0.65},"lqip":"data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoRwJoAD4udZKZSNrHo0gAD+8MyvGOgoKSodgQsKiAMm2iOQuC3ivwCcZoI3KX0GtOwEniOs+pl0D+EqSddayUSOiTJ0fTmpflRJxA3PKkIeARzgAAA="},
  "camera-pietra-lampada": {"category":"rooms","width":1080,"height":851,"widths":[480,800],"hash":"9d28d63f","focal":{"x":0.4,"y":0.65},"lqip":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAA0AA4BaJaACdAERH7VO6AAA/vEhYzbCN66mgOXFvcPpfvaNpqGfqReg1hiNwyCs8x1TuXasMJ4vZTdQXAAA"},
  "camera-copriletto-fiori": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"92d0de0b","focal":{"x":0.4,"y":0.6},"lqip":"data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAwAA4BaJbACdADjesSwFBV7wAD+QzhpfnRNMJN3w5Rv2mcSYashLSqHJzk2moLavAj9n720rwkLOFubg7eVaiQYMRUAAAA="},
  "camera-copriletto-fiori-scala": {"category":"rooms","width":1024,"height":768,"widths":[480,800],"hash":"b406b5db","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAwAA4BaJbACdADcOj23GEXAAP7sjdMD++LQqVFD07BJ8qiwfkwVxZAOFpeuGZAuEzvBl71LgAAA"},
  "arpista-nel-bosco": {"category":"events","width":1500,"height":2000,"widths":[480,800,1200],"hash":"6556732b","focal":{"x":0.55,"y":0.55},"lqip":"data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABUAPu1mqk2ppaQiMAgBMB2JYwC7ACBy8i83KTb40fAA61SK7GwDTvnZxcN//w6eE+c0ZqovKrnLINKDEIwVhSKeeAAA"},
  "cena-nel-bosco": {"category":"events","width":1064,"height":1445,"widths":[480,800],"hash":"136321e6","focal":{"x":0.55,"y":0.65},"lqip":"data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoQABYAPu1orU2ppqSiMAgBMB2JZAC7AGlgXclYyeTceqvPAAD+7uqxM4O5Umq4MQ3nJBYoxW3f4HzJz7J0DHpySwlxPcwsEEKVeywOLFyigzxTmLSWbH5uVdY+4lu48jmwDhujUAA="},
  "tavoli-giardino-rosa": {"category":"events","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"d5beed2e","focal":{"x":0.4,"y":0.55},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAwAA4BaJagCdAENo7tk//wAAP7p7d0TENb7jz4UyDdLXQvTAN8jWBFgxbomz3RnPk7BH1DqSzkh9sAAAA=="},
  "cena-a-lume-di-candela": {"category":"events","width":1078,"height":1391,"widths":[480,800],"hash":"bf8e69a3","focal":{"x":0.6,"y":0.6},"lqip":"data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABUAPu1iqU2ppaOyMAgCQB2JYwCsACHPhr1ephi2jhAA/uv0MJjYQjAHbe8Z9uTlFLq44Vus5Tlh4vJj+8licGCq20AA"},
  "cena-giardino-sera": {"category":"events","width":1080,"height":1234,"widths":[480,800],"hash":"67d1794c","focal":{"x":0.5,"y":0.6},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABQAwCdASoQABIAPu1iqU2ppaOvMAgB4B2JQBfnAtuNrDHioAD18aHVvtOfZTDBPWyaGcXeIEAspdafcGa3i5SYTKLAAA=="},
  "cena-luci-sera": {"category":"events","width":1080,"height":1265,"widths":[480,800],"hash":"fcb2edb1","focal":{"x":0.5,"y":0.7},"lqip":"data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABMAPu1iqU2ppaOiMAgBMB2JYgC7ACHZyHsfUSvfAAD+GHQJ1SZsdg+8JV77ObIOTkZGmXPBACE65gd1tUoyl0gnCsf2iAAAAA=="},
  "cascina-illuminata-sera": {"category":"events","width":1080,"height":603,"widths":[480,800],"hash":"c0fbe8bb","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAkAA4BaJagCdAEUoSQkiAAA/ukDDDYs6wVoqNweCjasXUcu2bG+gbv5rLiUq52AAA=="},
  "cascina-magnolia": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"0e240113","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAwAA4BaJYgCdADPm2uOiB5kAPHdiLSDcP9Rh4YVc/l7WiwSbnyT6TndoeWUNCGcLy6odozEAAAA"},
  "cascina-facciata-pietra": {"category":"landscape","width":1066,"height":1081,"widths":[480,800],"hash":"dd687c5e","focal":{"x":0.5,"y":0.5},"lqip":"data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQABAAA4BaJbACdACZbJgGgAD9RtXzAtcMcXPVra+sKm9ZoHuqmAai4ujMTJaWowafj0SQx76vQmM/qwcXym5TOiSAAA=="},
  "cascina-portico-estate": {"category":"landscape","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"118b7f10","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAwAA4BaJZgCdAERG8W4MgAA/mWXEK010v2Dwx94cYBbUpd1pGZZKDLh7zeYBTZBK3HlLGgAAA=="},
  "capre-al-pascolo": {"category":"goats","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"7214ab97","focal":{"x":0.5,"y":0.7},"lqip":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAwAA4BaJagCdAEO9KGtzgAA/nZ4/dls/LCrfUn6nj1Q8mK4S8bJctMExNeyhf4NCXpO39AoDpAAAAA="},
  "cancello-glicine": {"category":"landscape","width":1071,"height":1407,"widths":[480,800],"hash":"ead3d227","focal":{"x":0.45,"y":0.6},"lqip":"data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdACEl0c/jLp8mQAD9Qh2drXJW7TGeiQxffLHTiM6+uCsIYz/C71ZxHtKfVB5h7ashxRgfZZhl6I2hZeXv2lPWHgAA"},
  "cascina-dal-prato": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"bef411ee","focal":{"x":0.5,"y":0.55},"lqip":"data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAwAA4BaJbACdABzaGAA/kbtII67U3PFoH0z+Jwz9Al9CnN+4pxpYN3Kna2y356BVK4+sKyMhQAA"},
  "cortile-gerani": {"category":"landscape","width":2048,"height":1536,"widths":[480,800,1200,1600],"hash":"130b2ade","focal":{"x":0.35,"y":0.5},"lqip":"data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJaACdAC6fHXhIgAA/ZqAw8x+DQNA8V8SNYVEV/lACYdJUjL8pE+pPq2aq9se8LxYatx6MqiAAA=="},
  "capre-sotto-la-cascina": {"category":"goats","width":1536,"height":2048,"widths":[480,800,1200],"hash":"4f0bbc2f","focal":{"x":0.5,"y":0.75},"lqip":"data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZACw7B5qsMfDqvd34AD9H2kIfhojEeHTndFqJ8YRIDperN1vTQnG6TfMUumk9OGCtmrOyIvBUV+2SpD3MsI6wAA="},
  "capretto-nel-fieno": {"category":"goats","width":2000,"height":1500,"widths":[480,800,1200,1600],"hash":"d1dc1026","focal":{"x":0.4,"y":0.65},"lqip":"data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAwAA4BaJYgC7AEKKNAAAP39HBZmBtmuteWKxBOnvM/mAmYVJDn4UL+ORd8ZOYCA0YDgAAA="},
} as const satisfies Record<string, ImageEntry>;

export type ImageSlug = keyof typeof IMAGES;

/** Localized alt text. IDs are `img.<slug>.alt`. */
export const IMAGE_ALTS: Record<ImageSlug, string> = {
  "tramonto-colline": $localize`:@@img.tramonto-colline.alt:Cielo rosa e azzurro al tramonto sopra le colline e la pianura.`,
  "ingresso-cascina-magnolia": $localize`:@@img.ingresso-cascina-magnolia.alt:Ingresso della cascina in pietra, con i fiori di magnolia in primo piano.`,
  "cascina-prato-estate": $localize`:@@img.cascina-prato-estate.alt:La cascina in pietra su un prato verde, sotto un cielo azzurro.`,
  "sala-ristorante-tavolata": $localize`:@@img.sala-ristorante-tavolata.alt:Sala del ristorante con una lunga tavola apparecchiata e tovaglie a quadretti rossi.`,
  "sala-ristorante-camino": $localize`:@@img.sala-ristorante-camino.alt:Sala del ristorante con il camino, le travi di legno e i tavoli apparecchiati.`,
  "sala-ristorante-travi": $localize`:@@img.sala-ristorante-travi.alt:Tavolo apparecchiato davanti al camino, sotto le travi di legno.`,
  "tavola-margherite": $localize`:@@img.tavola-margherite.alt:Tavola apparecchiata vista dall'alto, con un centrotavola di margherite.`,
  "sala-ristorante-tavoli": $localize`:@@img.sala-ristorante-tavoli.alt:Tavoli apparecchiati nella sala del ristorante, con le pareti color terracotta.`,
  "sala-ristorante-fiori": $localize`:@@img.sala-ristorante-fiori.alt:Tavoli apparecchiati nella sala, con un vaso di fiori in primo piano.`,
  "sala-ristorante-angolo": $localize`:@@img.sala-ristorante-angolo.alt:Angolo della sala con una finestra, tavoli a quadretti e decorazioni.`,
  "tavolata-pergolato-fronte": $localize`:@@img.tavolata-pergolato-fronte.alt:Lunga tavola apparecchiata sotto il pergolato, con un calice in primo piano.`,
  "tavolata-pergolato": $localize`:@@img.tavolata-pergolato.alt:Lunga tavola apparecchiata all'aperto, sotto il pergolato e davanti al muro di pietra.`,
  "tavolo-finestra-gialla": $localize`:@@img.tavolo-finestra-gialla.alt:Tavolo all'aperto davanti a una finestra gialla, con gerani rossi e un muro di pietra.`,
  "cuscino-cuore-camera": $localize`:@@img.cuscino-cuore-camera.alt:Cuscino ricamato con un cuore rosso sul letto, davanti a un muro di pietra.`,
  "camera-scala-ferro": $localize`:@@img.camera-scala-ferro.alt:Camera con letto matrimoniale, soffitto di legno e una scala di ferro.`,
  "camera-pietra-letto-ferro": $localize`:@@img.camera-pietra-letto-ferro.alt:Camera con muro di pietra, letto in ferro battuto e lampada accesa.`,
  "camera-letto-ferro-verticale": $localize`:@@img.camera-letto-ferro-verticale.alt:Camera con letto in ferro battuto, muro di pietra e pavimento in cotto.`,
  "camera-pietra-lampada": $localize`:@@img.camera-pietra-lampada.alt:Camera con muro di pietra, letto in ferro battuto e lampada sul comodino.`,
  "camera-copriletto-fiori": $localize`:@@img.camera-copriletto-fiori.alt:Camera con copriletto a fiori, muro di pietra e finestra con vetri colorati.`,
  "camera-copriletto-fiori-scala": $localize`:@@img.camera-copriletto-fiori-scala.alt:Camera con copriletto a fiori, comò antico e scala a chiocciola.`,
  "arpista-nel-bosco": $localize`:@@img.arpista-nel-bosco.alt:Una musicista suona l'arpa nel bosco, accanto a un vaso di fiori.`,
  "cena-nel-bosco": $localize`:@@img.cena-nel-bosco.alt:Gruppo di persone a cena all'aperto, tra gli alberi del bosco.`,
  "tavoli-giardino-rosa": $localize`:@@img.tavoli-giardino-rosa.alt:Tavoli apparecchiati all'aperto con tovaglie rosa, tra gli alberi.`,
  "cena-a-lume-di-candela": $localize`:@@img.cena-a-lume-di-candela.alt:Tavoli a lume di candela all'aperto, di sera, con la pianura illuminata sullo sfondo.`,
  "cena-giardino-sera": $localize`:@@img.cena-giardino-sera.alt:Cena all'aperto di sera, con gli ospiti seduti ai lunghi tavoli sotto gli alberi.`,
  "cena-luci-sera": $localize`:@@img.cena-luci-sera.alt:Cena all'aperto di sera, sotto una fila di lucine appese tra gli alberi.`,
  "cascina-illuminata-sera": $localize`:@@img.cascina-illuminata-sera.alt:La cascina illuminata di sera, con gli ospiti sotto il portico.`,
  "cascina-magnolia": $localize`:@@img.cascina-magnolia.alt:La cascina in pietra vista dall'ingresso, con un albero di magnolia in fiore.`,
  "cascina-facciata-pietra": $localize`:@@img.cascina-facciata-pietra.alt:La facciata in pietra della cascina, con il balcone di legno e il cielo azzurro.`,
  "cascina-portico-estate": $localize`:@@img.cascina-portico-estate.alt:Il lato della cascina con il portico, il pergolato e il prato in estate.`,
  "capre-al-pascolo": $localize`:@@img.capre-al-pascolo.alt:Un gruppo di capre bianche al pascolo su un prato verde.`,
  "cancello-glicine": $localize`:@@img.cancello-glicine.alt:Il cancello della cascina con il glicine in fiore.`,
  "cascina-dal-prato": $localize`:@@img.cascina-dal-prato.alt:La cascina vista dal prato, tra alberi e fiori.`,
  "cortile-gerani": $localize`:@@img.cortile-gerani.alt:Il cortile in pietra con la facciata della cascina e vasi di gerani.`,
  "capre-sotto-la-cascina": $localize`:@@img.capre-sotto-la-cascina.alt:Capre bianche e marroni al pascolo sul prato sotto la cascina.`,
  "capretto-nel-fieno": $localize`:@@img.capretto-nel-fieno.alt:Un capretto bianco e nero riposa nel fieno, vicino a un tronco.`,
};
